joshaber/Few.swift

Few-Mac/Button.swift, Few-Mac/Image.swift, Few-Mac/Input.swift, Few-Mac/Label.swift, Few-Mac/Password.swift, Few-Mac/ScrollView.swift, Few-Mac/TableView.swift, FewCore/View.swift
=> Set `alphaValue` and `hidden` at creation.

FewCore/Component.swift, FewDemo/CustomButton.swift
=> Don't copy layout to the root

Few-Mac/Label.swift, Few-Mac/ScrollView.swift, Few-iOS/Label.swift, Few-iOS/ScrollView.swift, FewCore/Element.swift, FewDemo/AppDelegate.swift
Flip margin and padding vertical direction so that up and down are right by default on OS X.
=> Adjust margin and padding direction

FewCore/Component.swift, FewDemo/CustomButton.swift, FewDemo/Demo.swift, FewDemo/TemperatureConverter.swift
This way we can avoid
https://gist.github.com/joshaber/0978209efef7774393e0.
=> Work around subclass crash

Few-iOS/Button.swift, Few-iOS/Image.swift, Few-iOS/Input.swift, Few-iOS/ScrollView.swift, Few-iOS/TableView.swift, Few-iOS/View.swift, FewDemo-iOS/AppDelegate.swift, FewDemo-iOS/ViewController.swift
Most iOS files were based on spaces
EDIT: there's a bunch of pending pull requests right now, some of which contain spaces, so I may need to do another pass before this one gets merged. I'm just putting this here as a reminder.
=> Standardize indentation on tabs

FewCore/Component.swift
=> private(set) var Component.state 

Few-iOS/TableView.swift, FewDemo-iOS/ViewController.swift
=> Apply table view cell parent fix to iOS

Few-iOS/TableView.swift, FewDemo-iOS/ViewController.swift
=> iOS table view: support multiple sections

Few-iOS/TableView.swift, FewCore/Component.swift
Here's a couple small tweaks to the new stuff. A little more concise here, a little safer there. Hope it helps
=> Simpo tweaks

Few-iOS/TableView.swift
=> Fix iOS table view selection

.gitignore, FewCore/Component.swift
Recursion is fun but let's not let things get out of hand :wink:
=> findViewRecursively needed to be ended

Few.xcodeproj/project.pbxproj
Fixes #81.
Link to the framework the workspace builds.
=> Fix iOS demo app linking

FewCore/Component.swift
@joshaber If you're using self in `updateState` you might be doing it wrong, but hey, it's a free country ^^
=> Mark updateState & modifyState as @noescape

Few-iOS/Label.swift
=> iOS: set number of lines on Label

FewCore/RealizedElement.swift
=> Use rectByOffsetting to remove 3 lines

FewCore/Element.swift
This makes it a little clearer what gets done during diffing under what circumstances @joshaber
=> Clean up Element.applyDiff a little bit

Few-Mac/TableView.swift, Few-iOS/TableView.swift
=> Store the parent RealizedElement for each cell in the cell itself

Few-iOS/Button.swift, FewDemo-iOS/ViewController.swift
=> Make Button a lot more flexible

Few-iOS/Button.swift, FewDemo-iOS/ViewController.swift
=> Fix iOS demo build

FewCore/RealizedElement.swift
@joshaber I'm using Few in a production app and this would sure be nice.
=> Mark RealizedElement.layoutIfNeeded public
